// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrismHyxApp.Raman.Models;

#nullable disable

namespace PrismHyxApp.Raman.Migrations
{
    [DbContext(typeof(OilInfoDbContext))]
    [Migration("20230506082938_HyxDb")]
    partial class HyxDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2");

            modelBuilder.Entity("PrismHyxApp.Raman.Models.OilInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OilNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("OilType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredictValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SampleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SamplePart")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectrumInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OilInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "0#车柴",
                            OilType = "{\"TypeName\":\"柴油\",\"GradeName\":\"0#\"}",
                            SampleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Name = "-35#军柴",
                            OilType = "{\"TypeName\":\"柴油\",\"GradeName\":\"-35#\"}",
                            SampleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Name = "-50#军柴",
                            OilType = "{\"TypeName\":\"柴油\",\"GradeName\":\"-50#\"}",
                            SampleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Name = "茂名通用喷气燃料",
                            OilType = "{\"TypeName\":\"航煤\",\"GradeName\":\"3#喷气燃料\"}",
                            SampleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Name = "高闪点-驱三",
                            OilType = "{\"TypeName\":\"航煤\",\"GradeName\":\"高闪点喷气燃料\"}",
                            SampleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
